name: production deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - main

jobs:
  production:
    runs-on: ubuntu-latest
    steps:
      - name: setup github
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4

      - name: run markdown converter
        run: |
          cd scripts
          python markdown_converter.py
          cd ..

      - name: install vercel cli
        run: npm install --global vercel@latest

      - name: pull vercel environment variables
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: build vercel artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
        
      - name: deploy vercel artifacts
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}